[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://campus-connect-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour les fonctions serverless (optionnel)
[functions]
  directory = "netlify/functions"
