services:
  - type: web
    name: campus-connect-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python nltk_setup.py
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
