services:
  - type: web
    name: campus-connect-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python nltk_setup.py
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

  - type: static
    name: campus-connect-frontend
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishDir: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://campus-connect-api.onrender.com/api
